MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
  MASK_FORMER:
    TEST:
      # A larger windows_size can be used if there is more GPU memory.
      WINDOW_SIZE: 3
      WINDOW_INFERENCE: True
      TASK: 'vss'
DATASETS:
  DATASET_RATIO: [1.0, 0.5]
  DATASET_NEED_MAP: [False, False]
  DATASET_TYPE: ['image_semantic', 'video_semantic', ]
  DATASET_TYPE_TEST: ['video_semantic', ]
  # The categories of all datasets will be mapped to the categories of the last dataset
  TRAIN: ("human_sem_seg_train", "VSPW_vss_video_train")
  TEST: ("VSPW_vss_video_val",)
#  DATASET_RATIO: [1.0,]
#  DATASET_NEED_MAP: [False,]
#  DATASET_TYPE: ['video_semantic', ]
#  DATASET_TYPE_TEST: ['video_semantic', ]
#  # The categories of all datasets will be mapped to the categories of the last dataset
#  TRAIN: ("human_VSPW_vss_video_train",)
#  TEST: ("human_VSPW_vss_video_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (7000,)
  MAX_ITER: 10000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (240, 300, 360, 420, 480)
  MAX_SIZE_TRAIN: 768
  MIN_SIZE_TEST: 360
  SAMPLING_FRAME_NUM: 1

  SAMPLING_FRAME_SHUFFLE: False
  # MIN_SIZE_TRAIN_SAMPLING : ["range", "choice", "range_by_clip", "choice_by_clip"]
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  # RANDOM_FLIP : ["none", "horizontal", "flip_by_clip"]. "horizontal" is set by default.
  RANDOM_FLIP: "flip_by_clip"
  AUGMENTATIONS: []
  CROP:
    ENABLED: False
    TYPE: "absolute_range"
    SIZE: (384, 600)
  # For pseudo videos
  PSEUDO:
    AUGMENTATIONS: ['rotation']
    MIN_SIZE_TRAIN: (240, 300, 360, 420, 480)
    MAX_SIZE_TRAIN: 768
    CROP:
      ENABLED: False
      TYPE: "absolute_range"
      SIZE: (384, 600)
  LSJ_AUG:
    ENABLED: False
    IMAGE_SIZE: 768
    MIN_SCALE: 0.1
    MAX_SCALE: 2.0
TEST:
  EVAL_PERIOD: 0
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2
